security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            chain:
                providers: ['participant_provider', 'professional_provider']
        participant_provider:
            entity:
                class: App\Entity\Participant
                property: email
        professional_provider:
            entity:
                class: App\Entity\Professional
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
            logout:
                path: app_logout

    role_hierarchy:
        ROLE_ADMIN: [ROLE_PROFESSIONAL, ROLE_USER]
        ROLE_PROFESSIONAL: [ROLE_USER]
        ROLE_PARTICIPANT: [ROLE_USER]

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/compte, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10